language: ruby
install: bundle install --deployment --path vendor/bundle
before_script:
  - bundle exec rake db:setup
script:
  - bundle exec rake spec
  - bundle exec rake test:rubocop
services:
  - postgresql
addons:
  postgresql: '9.4'
