language: ruby
services:
  - postgresql
addons:
  postgresql: '9.4'
before_install:
  - openssl aes-256-cbc -K $encrypted_293bfe86302a_key -iv $encrypted_293bfe86302a_iv -in github_deploy_key.enc -out github_deploy_key -d
install: bundle install --deployment --path vendor/bundle
before_script:
  - |
    if [ -z "$SSH_KEY_REQUIRED" ]; then echo "Skipping SSH key setup"; exit 0; fi
    declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
    openssl aes-256-cbc -K $encrypted_293bfe86302a_key -iv $encrypted_293bfe86302a_iv -in "github_deploy_key.enc" -out "$SSH_FILE" -d
    chmod 600 "$SSH_FILE" \
      && printf "%s\n" \
           "Host github.com" \
           "  IdentityFile $SSH_FILE" \
           "  LogLevel ERROR" >> ~/.ssh/config
  - bundle exec rake db:setup
script:
  - bundle exec rake spec
  - bundle exec rake test:rubocop
