curl:
  weight: 1
  label: cURL
  lexer: sh
node:
  weight: 2
  label: Node.js
  lexer: javascript
java:
  weight: 3
  label: Java
  lexer: java
dotnet:
  weight: 4
  label: .NET
  lexer: c#
csharp:
  weight: 4
  label: C#
  lexer: c#
php:
  weight: 5
  label: PHP
  lexer: php
python:
  weight: 6
  label: Python
  lexer: python
ruby:
  weight: 7
  label: Ruby
  lexer: ruby
ncco:
  label: NCCO
  lexer: json
json:
  label: JSON
  lexer: json
xml:
  label: XML
  lexer: xml
