1: |-
    <h2>Welcome to Nexmo Developer <span class="beta">Beta</span></h2>
    <p>Nexmo Developer is a first look at how we are improving our Documentation, API references, learning resources & tooling to help you more effectively use our services. We want to help you to easily find the information you need to integrate Nexmo APIs into your code.</p>
    <p>As we start this transition, we’d love to hear from you with thoughts & suggestions. If you’ve got something, positive or negative, to tell us, please use the feedback tool. We will act on your feedback! - Nexmo</p>
