nexmo-community/nexmo-ruby-quickstart: 'master'
nexmo-community/nexmo-node-quickstart: 'master'
nexmo-community/nexmo-ruby-quickstart: 'master'
nexmo-community/nexmo-php-quickstart: 'master'
nexmo-community/nexmo-dotnet-quickstart: 'master'
nexmo-community/nexmo-java-quickstart: 'master'
